#pragma once

#include <stdint.h>

#include "sdkconfig.h"

#ifndef CONFIG_LORA_TEST_MODE
#define CONFIG_LORA_TEST_MODE 0
#endif

#if !defined(CONFIG_LORA_TEST_ROLE_ROOT) && !defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_ROOT 1
#define CONFIG_LORA_TEST_ROLE_NODE 0
#elif defined(CONFIG_LORA_TEST_ROLE_ROOT) && !defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_NODE 0
#elif !defined(CONFIG_LORA_TEST_ROLE_ROOT) && defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_ROOT 0
#endif

#ifndef CONFIG_LORA_TEST_FREQUENCY_MHZ
#define CONFIG_LORA_TEST_FREQUENCY_MHZ 915
#endif

#ifndef CONFIG_LORA_TEST_BANDWIDTH_KHZ
#define CONFIG_LORA_TEST_BANDWIDTH_KHZ 125
#endif

#ifndef CONFIG_LORA_TEST_SPREADING_FACTOR
#define CONFIG_LORA_TEST_SPREADING_FACTOR 7
#endif

#ifndef CONFIG_LORA_TEST_TX_POWER_DBM
#define CONFIG_LORA_TEST_TX_POWER_DBM 10
#endif

#ifndef CONFIG_LORA_TEST_NODE_SEND_INTERVAL_MS
#define CONFIG_LORA_TEST_NODE_SEND_INTERVAL_MS 2000
#endif

#ifndef CONFIG_LORA_TEST_NODE_SEND_JITTER_MS
#define CONFIG_LORA_TEST_NODE_SEND_JITTER_MS 250
#endif

#ifndef CONFIG_LORA_TEST_ROOT_SUMMARY_INTERVAL_MS
#define CONFIG_LORA_TEST_ROOT_SUMMARY_INTERVAL_MS 10000
#endif

#define LORA_TEST_PIN_SCK 5
#define LORA_TEST_PIN_MISO 19
#define LORA_TEST_PIN_MOSI 27
#define LORA_TEST_PIN_CS 18
#define LORA_TEST_PIN_RST 14
#define LORA_TEST_PIN_DIO0 26

#define LORA_TEST_FREQUENCY_HZ ((uint32_t)CONFIG_LORA_TEST_FREQUENCY_MHZ * 1000000UL)
#define LORA_TEST_BANDWIDTH_HZ ((uint32_t)CONFIG_LORA_TEST_BANDWIDTH_KHZ * 1000UL)
