#pragma once

#include <stdint.h>

#include "sdkconfig.h"

#ifndef CONFIG_LORA_TEST_MODE
#define CONFIG_LORA_TEST_MODE 0
#endif

#if !defined(CONFIG_LORA_TEST_ROLE_ROOT) && !defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_ROOT 1
#define CONFIG_LORA_TEST_ROLE_NODE 0
#elif defined(CONFIG_LORA_TEST_ROLE_ROOT) && !defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_NODE 0
#elif !defined(CONFIG_LORA_TEST_ROLE_ROOT) && defined(CONFIG_LORA_TEST_ROLE_NODE)
#define CONFIG_LORA_TEST_ROLE_ROOT 0
#endif

#ifndef CONFIG_LORA_TEST_FREQUENCY_MHZ
#define CONFIG_LORA_TEST_FREQUENCY_MHZ 915
#endif

#ifndef CONFIG_LORA_TEST_NODE_SEND_INTERVAL_MS
#define CONFIG_LORA_TEST_NODE_SEND_INTERVAL_MS 2000
#endif

#ifndef CONFIG_LORA_TEST_NODE_SEND_JITTER_MS
#define CONFIG_LORA_TEST_NODE_SEND_JITTER_MS 250
#endif

#ifndef CONFIG_LORA_TEST_ROOT_SUMMARY_INTERVAL_MS
#define CONFIG_LORA_TEST_ROOT_SUMMARY_INTERVAL_MS 10000
#endif

/*
 * Fallbacks dos simbolos do modulo EBYTE E220 (caso o menu Kconfig nao esteja
 * presente em um dado build). Os pinos sao fixos no codigo (E220_PIN_* em
 * e220_lora.h). Os bool ficam indefinidos quando "n" no Kconfig, dai o
 * #ifndef -> 0.
 */
#ifndef CONFIG_FLOW_E220_UART_PORT
#define CONFIG_FLOW_E220_UART_PORT 1
#endif
#ifndef CONFIG_FLOW_E220_BAUD
#define CONFIG_FLOW_E220_BAUD 9600
#endif
#ifndef CONFIG_FLOW_E220_ADDRESS
#define CONFIG_FLOW_E220_ADDRESS 0
#endif
#ifndef CONFIG_FLOW_E220_CHANNEL
#define CONFIG_FLOW_E220_CHANNEL 65
#endif
#ifndef CONFIG_FLOW_E220_AIR_DATA_RATE
#define CONFIG_FLOW_E220_AIR_DATA_RATE 2
#endif
#ifndef CONFIG_FLOW_E220_TX_POWER_DBM
#define CONFIG_FLOW_E220_TX_POWER_DBM 22
#endif
#ifndef CONFIG_FLOW_E220_WOR_PERIOD_MS
#define CONFIG_FLOW_E220_WOR_PERIOD_MS 0
#endif
#ifndef CONFIG_FLOW_E220_FIXED_MODE
#define CONFIG_FLOW_E220_FIXED_MODE 0
#endif
#ifndef CONFIG_FLOW_E220_RSSI_BYTE
#define CONFIG_FLOW_E220_RSSI_BYTE 0
#endif

#define LORA_TEST_FREQUENCY_HZ ((uint32_t)CONFIG_LORA_TEST_FREQUENCY_MHZ * 1000000UL)
